### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by iLynette** [iLynette/space-x#25]
We are a team of three.

Link to project: https://github.com/iLynette/space-x/projects/1

**Comment by elisha2kyakpo1** [comment]
Hi 👋 @iLynette, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

I'm wishing you "coders" the best 👍

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by iLynette** [comment]
Thank you @elisha2kyakpo1
